name: compile

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.RSA_PRIVATE_KEY }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with: { node-version: 22 }
      - run: npm install --no-save --no-audit --no-fund --no-progress typescript@4.2 @types/jquery
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - run: python compile.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          default_author: github_actions
          message: "[bot] Build JavaScripts"
